# Generated by Django 4.0.3 on 2022-03-14 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blockedlist_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_token', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('traceback', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 14, 20, 36, 33, 599658))),
            ],
            options={
                'verbose_name': 'Временная страница',
                'verbose_name_plural': 'Временные страницы',
            },
        ),
    ]
