# Generated by Django 4.0.3 on 2022-03-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_temporarypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryPage',
        ),
    ]
